# Generated by Django 4.2.2 on 2023-06-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoTask', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AddField(
            model_name='task',
            name='taskId',
            field=models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False),
        ),
    ]
