# Generated by Django 4.2.2 on 2023-06-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoTask', '0002_remove_task_id_task_taskid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktag',
            name='id',
        ),
        migrations.AddField(
            model_name='tasktag',
            name='tegId',
            field=models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskTag',
            field=models.IntegerField(default=0),
        ),
    ]
