# Generated by Django 4.2.2 on 2023-06-19 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoTask', '0003_remove_tasktag_id_tasktag_tegid_alter_task_tasktag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskTag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDoTask.tasktag'),
        ),
    ]
